language: c fortran
sudo: required
before_install:
  - sudo apt-get install gfortran cmake

script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=DEBUG ..
- make

after_success:
  - bash <(curl -s https://codecov.io/bash)
